name: Test secret scanning of github workflows
on: 
  workflow_dispatch:

# Declare default permissions as read only.
permissions: read-all

jobs:
  lets-leak-fake-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Output fake AWS access key
      run: |
        echo "AKIAJSIE27KKMHXI3BJQ"

  search-logs-for-secrets:
    runs-on: ubuntu-latest
    needs: lets-leak-fake-secrets
    if: always()
    steps:
    - name: Create logs folder
      run: |
        mkdir -p workflow_logs
    - name: Obtain a Secret Scanning Bot GitHub App Installation Access Token
      run: |
        TOKEN="$(npx obtain-github-app-installation-access-token@1.1.0 ci ${{ secrets.GH_APP_CREDENTIALS_TOKEN }})"
        echo "::add-mask::$TOKEN"
        echo "GITHUB_TOKEN=$TOKEN" >> $GITHUB_ENV        
    - name: Retrieve GitHub Action workflows logs
      uses: mohamed-cds/write-action-logs-to-file@1.0.0
      with:
        github_token: ${{ env.GITHUB_TOKEN }}
        github_org: ${{ github.repository_owner }}
        github_repository: ${{ github.event.repository.name }}
        github_run_id: "${{ github.run_id }}"
        logs_output_path: "workflow_logs/output.txt"
    - name: Search GitHub Action workflows logs for secrets
      uses: trufflesecurity/trufflehog@v3.3.3
      with:
          path: workflow_logs/
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
    