name: Sync SRE files
on: 
  workflow_dispatch:

jobs:
  sync_backup_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: impersonate SRE Read/Write GH App
        uses: tibdex/github-app-token@7ce9ffdcdeb2ba82b01b51d6584a6a85872336d4
        id: generate_token
        with:
          app_id: ${{ secrets.SRE_READWRITE_APP_ID }}
          private_key: ${{ secrets.SRE_READWRITE_APP_PRIVATE_KEY }}
      - name: Sync SRE Workflows
        uses: BetaHuhn/repo-file-sync-action@878d649c33c834dc1eff4c00f7fcf16bf281eb63
        with:
          GH_INSTALLATION_TOKEN: ${{ steps.generate_token.outputs.token }}
          CONFIG_PATH: tools/sre_file_sync/sync.yml
          ASSIGNEES: CalvinRodo
          GIT_EMAIL: sre-and-tech-ops@cds-snc.ca
          GIT_USERNAME: CalvinRodo



